### ISSUE TITLE
Create "develop" branch

### ISSUE THREAD

**Issue by i-am-offline** [SmartVisuTNG/smartvisu#19]
A "develop" branch should be created. PRs can be merged and tested there, while the master branch should contain a "stable" version. Probably use similar release management scheme as SmartHomeNG (https://github.com/smarthomeNG/smarthome/wiki/ReleaseManagement)

**Comment by smaiLee** [comment]
This is planned as soon as 2.9 is feature freeze / public beta (see https://knx-user-forum.de/forum/supportforen/smartvisu/977954-neuer-fork-smartvisutng-es-geht-weiter?p=978122#post978122)
At the moment the master branch itself can not be seen as stable because its a fork of the development version 2.8.
So IMHO there's no reason for a develop branch now. But please tell me, if you don't follow my opinion and see a reason, then i will create the branch.

**Comment by i-am-offline** [comment]
OK, thats an acceptable reason.
